name: "Workflow Dispatch"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  call-build:
    name: "Build"
    needs: call-lint
    uses: ./.github/workflows/build.yml
    secrets: inherit

  call-tests:
    name: "Tests"
    needs: call-build
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  call-check-version:
    name: "Check Version"
    needs: call-tests
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
    uses: ./.github/workflows/check-version.yml
    secrets: inherit

  call-release:
    name: "Release"
    needs: call-check-version
    if: ${{ needs.call-check-version.outputs.changed == 'true' }}
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.call-check-version.outputs.version }}
    secrets: inherit
