name: "Tests"
on:
  workflow_call:
defaults:
  run:
    shell: bash
env:
  RUNNER_BIN_DIR: /home/runner/.local/bin
permissions:
  contents: write
  packages: read
  checks: write

jobs:

  integration-tests:
    name: "Integration Tests"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Download binary artifact
        run: |
          mkdir -p ${{ env.RUNNER_BIN_DIR }}
          wget -c https://github.com/cheqd/cheqd-node/releases/download/v1.0.4-develop.1/cheqd-noded-1.0.4-develop.1-Linux-x86_64.tar.gz
          tar -xvf cheqd-noded-1.0.4-develop.1-Linux-x86_64.tar.gz -C ${{ env.RUNNER_BIN_DIR }}
          sudo chmod +x ${{ env.RUNNER_BIN_DIR }}/cheqd-noded

      - name: Restore binary permissions
        run: sudo chmod +x ${{ env.RUNNER_BIN_DIR }}/cheqd-noded

      - name: Generate localnet configs
        working-directory: ./docker/localnet
        run: |
          bash gen-network-config.sh
          sudo chown -R 1000:1000 network-config

      - name: Set up Docker localnet
        working-directory: ./docker/localnet
        run: |
          docker compose --env-file build-latest.env up --detach --no-build

      - name: Import keys
        working-directory: ./docker/localnet
        run: |
          bash import-keys.sh
      
      - name: Run Tests
        run: npm test